= 1.3 Storing data with data connections

include::_attributes.adoc[]

xref:index.adoc[Back to the introduction]

For this {deliverable}, you need S3-compatible object storage, such as Ceph, Minio, or AWS S3, to store the data and models. To access the data and models, you create data connections, resources that contain the configuration parameters that are required to connect to an object storage bucket.

You need the following two storage buckets:

* *My Storage* - Use this bucket for storing your models and data. You can reuse this bucket and its connection for your notebooks and model servers.  
*  *Pipelines Artifacts* - Use this bucket as storage for your pipeline artifacts. A pipeline artifacts bucket is required when you create a pipeline server.  For this {deliverable}, we create this bucket to separate it from the first storage bucket for clarity.

You have two options for creating these storage buckets:

* If you want to use your own S3-compatible object storage buckets, create data connections to them as described in xref:1-03-01-data-connections-manual.adoc[Creating data connections to your own S3-compatible object storage].

* If you want to run a script that installs local Minio storage buckets and creates data connections to them, for the purposes of this {deliverable}, follow the steps in xref:1-03-02-data-connections-script.adoc[Running a script to install local object storage buckets and create data connections].