= Fraud Detection Workshop with Red Hat OpenShift Data Science
:page-layout: home
:!sectids:

[.text-center.strong]
== Introduction

Welcome!

In this workshop, you'll learn an easy way to incorporate data science and AI/ML into an OpenShift development workflow.

You'll use an example fraud detection model to complete the following tasks:

* Explore a pre-trained fraud detection model by using Jupyter Notebooks.
* Deploy the model by using OpenShift Data Science model serving.
* Integrate the model into a real-time fraud detection application.
* Refine and train the model by using automated pipelines.

And you'll do all of this without having to install anything on your own computer, thanks to https://www.redhat.com/en/technologies/cloud-computing/openshift/openshift-data-science[Red Hat OpenShift Data Science].


//add a description of the fraud detection model and how it works?

=== Before you begin

https://developers.redhat.com/products/red-hat-openshift-data-science/download[Set up your Red Hat OpenShift Data Science environment]

If you don't already have an instance of Red Hat OpenShift Data Science, find out more on the https://developers.redhat.com/products/red-hat-openshift-data-science/download[developer page].  There, you can spin up your own account on the *free OpenShift Data Science Sandbox* or learn about installing on *your own OpenShift cluster*.

If you're ready, xref:1-01-dashboard.adoc[start the workshop!]
